### ISSUE TITLE
Running Tests

### ISSUE THREAD

**Issue by AbsoLouie** [RequestNetwork/RequestVesting#2]
Hello,

I just forked the repo and attempted to run the tests from the Truffle Console. I noticed that `deposit.js` is complaining about not finding the module `bignumber.js`

Is that a custom file or a reference to https://github.com/MikeMcl/bignumber.js/

Cheers

**Comment by vrolland** [comment]
Hello Louiedp3,

Thank you for your concern. 
Yes, it's a reference to https://github.com/MikeMcl/bignumber.js.

I updated the readme.

Cheers,
